### ISSUE TITLE
Nvidia GPU is not shown

### ISSUE THREAD

**Issue by ih8d8** [HikariKnight/ls-iommu#3]
I have a Lenovo Ideapad 5 15ITL05 laptop with Intel TigerLake-LP GT2 [Iris Xe Graphics] and  NVIDIA GeForce MX450.

When I run the command ` lspci -nn | grep NVIDIA` , it lists my NVIDIA GPU:
`01:00.0 3D controller [0302]: NVIDIA Corporation TU117M [GeForce MX450] [10de:1f97] (rev a1)`

However, the output of  `ls-iommu -g` only shows my Intel integrated GPU:
`IOMMU Group   0: 0000:00:02.0 VGA compatible controller [0300] Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01)`

I saw [this](https://github.com/HikariKnight/ls-iommu/blob/0164ea673fb94bc7f5d498dba26de95f150cd5a5/main.go#L16) in your code. Does this mean my laptop does not support GPU passthrough because of Nvidia being "3D controller" and not "VGA compatible controller"?

**Comment by HikariKnight** [comment]
yes 3D controllers are not supported since they rely on the igpu to even function, i can however make a flag to show 3d controllers so people who want to experiment (and most likely crash their system) can still try as i have heard of a total of 2 people who have managed to make it work (although not great)

**Comment by HikariKnight** [comment]
nevermind @ih8d8, 3D controllers dont work at all since you cant make them realize there is a monitor connected (or internal display) because that is handled by the igpu.
you can follow the whole rabbit hole here
https://lantian.pub/en/article/modify-computer/laptop-intel-nvidia-optimus-passthrough.lantian/

So just to avoid confusion (until a way to make it actually properly work with passing through 3D controllers) i will make a flag with a warning or just keep ignoring 3D controllers.

**Comment by ih8d8** [comment]
Yeah, I saw that blog post yesterday and concluded it's way more complicated than I thought so I just gave up on it. Thanks for your replies though.

**Comment by HikariKnight** [comment]
no problem
